defaults: &defaults
  docker:
    - image: sedzsoft/vof-ci-image
      environment:
        - VOF_PATH=~/vof
        - PG_HOST=localhost
        - PG_USER=ubuntu
        - RAILS_ENV=test
        - RACK_ENV=test
    - image: postgres:9.5
      environment:
        - POSTGRES_USER=ubuntu
        - POSTGRES_DB=db_name

  working_directory: ~/vof

version: 2
jobs:
  build:
    docker:
      - image: sedzsoft/vof-ci-image:latest
    working_directory: ~/vof
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install System Dependencies
          command: sudo apt-get update -qq && sudo apt-get install -y build-essential postgresql libpq-dev rake
      - run:
          name: Install bundler
          command: |
            sudo gem install bundler
            $HOME/.rubies/ruby-2.4.1/bin/bundle
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run: 
          name: Set up DB
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
          environment:
            DATABASE_URL: "postgres://ubuntu@localhost:5432/db_name"    
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
        keys:
        - v1-dependecies-{{ checksum "Gemfile.lock" }}
        - v1-dependecies-
      - run:
          name: run tests
          steps:
          minitest_globs:
            - test/
          command: |
            set +e
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"          
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            "${TEST_FILES}"
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

