dependencies:
  pre:
    - curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - sudo dpkg -i google-chrome.deb
    - sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
    - rm google-chrome.deb

version: 2
jobs:
  build:
    docker:
      - image: ruby:2.4.1
        environment:
          - VOF_PATH: ~/vof
          - PG_HOST: localhost
          - PGUSER: circleci
          - RAILS_ENV: test
          - DATABASE_URL: postgresql://circleci@localhost/circlecidb
      - image: postgres:9.6
        environment:
          - POSTGRES_USER: circleci
          - POSTGRES_DB: circlecidb
          - POSTGRES_PASSWORD: ‘’

    working_directory: ~/vof

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum “Gemfile.lock” }}
          - v1-dependencies-
      - save_cache:
          paths:
          - ./vendor/bundle
          key: v1-dependencies-{{ checksum “Gemfile.lock” }}

      - run:
          name: Install System Dependencies
          command: apt-get update -qq && apt-get install -y build-essential postgresql libpq-dev nodejs rake sudo
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run:
          name: Set up DB
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
          environment:
            DATABASE_URL: "postgres://circleci@localhost:5432/circlecidb"
      - run:
          name: Install JS runtime
          command: sudo apt-get install -y nodejs
      - run:
          name: Install bundler
          command: |
            sudo gem install --no-ri --no-rdoc bundler
            bundle install
      - run:
          name: start postgres server
          command: sudo service postgresql start
                  
  test:
    docker:
      - image: ruby:2.4.1
        environment:
          - VOF_PATH: ~/vof
          - PG_HOST: localhost
          - PGUSER: circleci
          - RAILS_ENV: test
          - DATABASE_URL: postgresql://circleci@localhost/circlecidb
      - image: circleci/postgres:9.6
        environment:
          - POSTGRES_USER: circleci
          - POSTGRES_DB: circlecidb
          - POSTGRES_PASSWORD: ‘’

    working_directory: ~/vof      

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum “Gemfile.lock” }}
          - v1-dependencies-
      - save_cache:
          paths:
          - ./vendor/bundle
          key: v1-dependencies-{{ checksum “Gemfile.lock” }}
      - run:
          name: Install System Dependencies
          command: apt-get update -qq && apt-get install -y build-essential nodejs rake sudo
      - run:
          name: Install bundler
          command: |
            sudo gem install --no-ri --no-rdoc bundler
            bundle install
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Install webdriver and selenium
          command: |
            sudo gem install selenium-webdriver chromedriver-helper
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run: 
          name: run tests
          command: |
            mkdir /tmp/test-results
            bundle exec rake spec

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  version: 2
  build_test and_deployment:
    jobs:
      - build
      - test:
          requires:
            - build

