version: 2
jobs:
  build:
    docker:
      - image: ruby:2.4.1
        environment:
          - VOF_PATH: ~/vof
          - PG_HOST: localhost
          - PGUSER: vof-tracker
          - RAILS_ENV: test
          - RACK_ENV: test
          - DATABASE_URL: postgresql://vof-tracker@localhost/vof-tracker
      - image: circleci/postgres:9.6
        environment:
          - POSTGRES_USER: vof-tracker
          - POSTGRES_DB: vof-tracker
          - POSTGRES_PASSWORD: ''
    docker:
      - image: ruby:2.4.1
    working_directory: ~/vof
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install System Dependencies
          command: apt-get update -qq && apt-get install -y build-essential postgresql libpq-dev rake sudo
      - run:
          name: Install JS runtime
          command: sudo apt-get install -y nodejs
      - run:
          name: Install bundler
          command: |
            sudo gem install --no-ri --no-rdoc bundler
            bundle install 
      - run:
          name: start postgres server
          command: sudo service postgresql start
      - run: 
          name: Set up DB
          command: |
            bundle exec rake db:create db:schema:load --trace db:migrate
            
  test:
    docker:
      - image: ruby:2.4.1
        environment:
          - VOF_PATH: ~/vof
          - PG_HOST: 5432
          - PGUSER: vof-tracker
          - RAILS_ENV: test
          - RACK_ENV: test
          - DATABASE_URL: postgresql://vof-tracker@localhost/circlecidb
      - image: circleci/postgres:9.6
        environment:
          - POSTGRES_USER: vof-tracker
          - POSTGRES_DB: vof-tracker
          - POSTGRES_PASSWORD: ''

    working_directory: ~/vof      

    steps:
      - checkout
      - restore_cache:
        keys:
        - v1-dependecies-{{ checksum "Gemfile.lock" }}
        - v1-dependecies-
      - run:
          name: run tests
          steps:
          minitest_globs:
            - test/
          command: |
            set +e
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"          
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            "${TEST_FILES}"
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

