defaults: &defaults
  docker:
    - image: sedzsoft/vof-ci-image
      environment:
        PGUSER: 
        RAILS_ENV: test
        DATABASE_URL: 

    - image: circleci/postgres:9.6
      environment:
        adapter: postgresql
        encoding: unicode
        username: <%= ENV['POSTGRES_USER'] %>
        password: <%= ENV['POSTGRES_PASSWORD'] %>
        host: <%= ENV['POSTGRES_HOST'] %>
        database: <%= ENV['POSTGRES_TEST_DB'] %>

  working_directory: ~/app

version: 2
jobs:
  build:
    docker:
       - image: sedzsoft/vof-ci-image
    working_directory: ~/vof

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
        
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

   setup vof source code:
     <<: *defaults
      - run:
          name: clone the code
          steps:
          - checkout
          - restore_cache:
            keys:
            - v1-dependecies-{{ checksum "Gemfile.lock" }}
            - v1-dependecies-
            command: |
              git clone https://github.com/andela/vof-tracker.git

   test:
     <<: *defaults
      - run:
          name: run tests
          steps:
          - checkout
          - restore_cache:
            keys:
            - v1-dependecies-{{ checksum "Gemfile.lock" }}
            - v1-dependecies-

          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            "${TEST_FILES}"

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results